/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariopapeleria;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ponce
 */
public class frmProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmProductos.class.getName());

    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
    }

    //Variable para guardar temporalmente los datos del registro original a editar
    clsProductos updateProductos;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        IblCodigo = new javax.swing.JLabel();
        IblDescripcion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IblPrecio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        IblIDProducto = new javax.swing.JLabel();
        IblPrecio1 = new javax.swing.JLabel();
        IblColor = new javax.swing.JLabel();
        IblTipoProducto = new javax.swing.JLabel();
        IblNombreProducto = new javax.swing.JLabel();
        IblCantidad = new javax.swing.JLabel();
        txtIDProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtTipoProducto = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPrecio1 = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreProducto1 = new javax.swing.JTextField();
        txtColor1 = new javax.swing.JTextField();
        txtCantidad1 = new javax.swing.JTextField();
        txtTipoProducto1 = new javax.swing.JTextField();
        IblTipoProducto1 = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JTextField();
        IblColor1 = new javax.swing.JLabel();
        txtIDProducto1 = new javax.swing.JTextField();
        IblNombreProducto1 = new javax.swing.JLabel();
        IblPrecio2 = new javax.swing.JLabel();
        IblCantidad1 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        IblIDProducto1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList<>();
        IblCantidad3 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JTextField();
        btnGuardar2 = new javax.swing.JButton();
        IblCantidad2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        IblIDProducto2 = new javax.swing.JLabel();
        IblTipoProducto2 = new javax.swing.JLabel();
        IblNombreProducto2 = new javax.swing.JLabel();
        IblPrecio3 = new javax.swing.JLabel();
        IblCantidad4 = new javax.swing.JLabel();
        IblColor2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiImportar = new javax.swing.JMenuItem();
        jmiExportar = new javax.swing.JMenuItem();
        jmiGenerarReporte = new javax.swing.JMenuItem();
        jmiReporteBonito = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel7.setText("Codigo:");

        IblCodigo.setText("jLabel8");

        IblDescripcion.setText("jLabel8");

        jLabel10.setText("Descripcion:");

        IblPrecio.setText("jLabel8");

        jLabel12.setText("Precio:");

        jButton2.setText("Eliminar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(IblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(IblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(IblPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel2.setText("Busqueda por Codigo:");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(this::btnBuscar1ActionPerformed);

        jLabel3.setText("Busqueda por Codigo:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Registro Productos");

        IblIDProducto.setText("ID Producto:");

        IblPrecio1.setText("Precio:");

        IblColor.setText("Color:");

        IblTipoProducto.setText("Tipo Producto:");

        IblNombreProducto.setText("Nombre Producto:");

        IblCantidad.setText("Cantidad:");

        txtIDProducto.addActionListener(this::txtIDProductoActionPerformed);

        txtNombreProducto.addActionListener(this::txtNombreProductoActionPerformed);

        txtTipoProducto.addActionListener(this::txtTipoProductoActionPerformed);

        txtColor.addActionListener(this::txtColorActionPerformed);

        txtPrecio1.addActionListener(this::txtPrecio1ActionPerformed);

        txtCantidad.addActionListener(this::txtCantidadActionPerformed);

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IblIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IblTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoProducto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IblNombreProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(IblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(IblPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblIDProducto)
                    .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblNombreProducto)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblTipoProducto)
                    .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblPrecio1)
                    .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtNombreProducto1.addActionListener(this::txtNombreProducto1ActionPerformed);

        txtColor1.addActionListener(this::txtColor1ActionPerformed);

        txtCantidad1.addActionListener(this::txtCantidad1ActionPerformed);

        txtTipoProducto1.addActionListener(this::txtTipoProducto1ActionPerformed);

        IblTipoProducto1.setText("Tipo Producto:");

        txtPrecio2.addActionListener(this::txtPrecio2ActionPerformed);

        IblColor1.setText("Color:");

        txtIDProducto1.addActionListener(this::txtIDProducto1ActionPerformed);

        IblNombreProducto1.setText("Nombre Producto:");

        IblPrecio2.setText("Precio:");

        IblCantidad1.setText("Cantidad:");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        IblIDProducto1.setText("ID Producto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(IblIDProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)
                            .addComponent(txtIDProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(IblTipoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtTipoProducto1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(IblNombreProducto1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(IblColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(btnActualizar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IblPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(IblCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblIDProducto1)
                    .addComponent(txtIDProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblNombreProducto1)
                    .addComponent(txtNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblTipoProducto1)
                    .addComponent(txtTipoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblColor1)
                    .addComponent(txtColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblPrecio2)
                    .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblCantidad1)
                    .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addContainerGap())
        );

        jLabel5.setText("Actualizacion  Productos");

        lstProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProductos.addListSelectionListener(this::lstProductosValueChanged);
        jScrollPane1.setViewportView(lstProductos);

        IblCantidad3.setText("Busqueda por codigo");

        txtCantidad2.addActionListener(this::txtCantidad2ActionPerformed);

        btnGuardar2.setText("Buscar");
        btnGuardar2.addActionListener(this::btnGuardar2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(IblCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblCantidad3)
                    .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        IblCantidad2.setText("Consultar producto");

        jLabel1.setText("ID Producto:");

        jLabel6.setText("Nombre Producto:");

        jLabel8.setText("Tipo Producto: ");

        jLabel9.setText("Precio:");

        jLabel11.setText("Cantidad:");

        jLabel14.setText("Color:");

        IblIDProducto2.setText("jLabel15");

        IblTipoProducto2.setText("jLabel15");

        IblNombreProducto2.setText("jLabel15");

        IblPrecio3.setText("jLabel15");

        IblCantidad4.setText("jLabel15");

        IblColor2.setText("jLabel15");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IblCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblTipoProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblIDProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblNombreProducto2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IblColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(17, 17, 17))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IblIDProducto2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(IblNombreProducto2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IblTipoProducto2))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(IblColor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IblPrecio3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(IblCantidad4))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel13.setText("Eliminar Articulo ");

        jmArchivo.setText("Archivo");

        jmiImportar.setText("Importar CSV");
        jmiImportar.addActionListener(this::jmiImportarActionPerformed);
        jmArchivo.add(jmiImportar);

        jmiExportar.setText("Exportar JSON");
        jmiExportar.addActionListener(this::jmiExportarActionPerformed);
        jmArchivo.add(jmiExportar);

        jmiGenerarReporte.setText("Generar Reporte PDF");
        jmiGenerarReporte.addActionListener(this::jmiGenerarReporteActionPerformed);
        jmArchivo.add(jmiGenerarReporte);

        jmiReporteBonito.setText("Reporte Bonito (PDF)");
        jmiReporteBonito.addActionListener(this::jmiReporteBonitoActionPerformed);
        jmArchivo.add(jmiReporteBonito);

        jMenuBar1.add(jmArchivo);

        jMenu2.setText("Informacion");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(IblCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IblCantidad2)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Estas seguro que deseas eliminar el registro " + "?",
                "Eliminacion de producto",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //Si la respuesta es SI comienza a eliminar el registro 
        if(respuesta ==JOptionPane.YES_OPTION){
            updateProductos.eliminar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIDProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void txtTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProductoActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clsProductos cProducto = new clsProductos (txtIDProducto1.getText(), txtNombreProducto1.getText(), txtTipoProducto1.getText(), txtColor1.getText(),  Double.parseDouble(IblPrecio1.getText()), txtCantidad1.getText());
        cProducto.guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
         updateProductos.actualizar(txtIDProducto1.getText(), txtNombreProducto1.getText(), txtTipoProducto1.getText(), txtColor1.getText(), IblPrecio1.getText(), txtCantidad1.getText());
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIDProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProducto1ActionPerformed

    private void txtNombreProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProducto1ActionPerformed

    private void txtTipoProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProducto1ActionPerformed

    private void txtColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColor1ActionPerformed

    private void txtPrecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio2ActionPerformed

    private void txtCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        clsProductos cProductos = new clsProductos();
        lstProductos.setModel(cProductos.llenarLista());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        clsProductos cProductos = new clsProductos();
        lstProductos.setModel(cProductos.llenarLista());
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad2ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        clsProductos cProducto = new clsProductos(txtIDProducto1.getText(), txtNombreProducto1.getText(), txtTipoProducto1.getText(), txtColor1.getText(), Double.parseDouble(txtPrecio1.getText()), txtCantidad1.getText());
        cProducto.guardar();
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void lstProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductosValueChanged
       //Asegura que seleccionamos un objeto de la lista
        if(!evt.getValueIsAdjusting()){
            //le asigna el valor de la lista seleccionado a la variable
            String registroSeleccionado = lstProductos.getSelectedValue();
            // separar los datos por el caracter especial
            String[] datos = registroSeleccionado.split("\\|");
            // Preparamos los datos pora mostrar limpios
            String idproducto = datos[0].replace("IDProducto: ", "");
            String nombreproducto = datos[1].replace(" NombreProducto: ", "");
            String tipoproducto = datos[2].replace(" TipoProducto: ", "");
            String color = datos[3].replace("Color: ", "");
            String precio = datos[4].replace(" Precio: ", "");
            String cantidad = datos[5].replace(" Cantidad: ", "");
            txtIDProducto1.setText(idproducto);
            txtNombreProducto1.setText(nombreproducto);
            txtTipoProducto1.setText(tipoproducto);
            txtColor1.setText(color);
            txtPrecio2.setText(precio);
            txtCantidad1.setText(cantidad);
        // llenamos los label de eliminar articulo
        IblIDProducto.setText(idproducto);
        IblNombreProducto.setText(nombreproducto);
        IblTipoProducto.setText(tipoproducto);
        IblColor.setText(color);
        IblPrecio.setText(precio);
        IblCantidad.setText(cantidad);
        // llenamos el objeto con los valores originales
        updateProductos = new clsProductos(idproducto, nombreproducto, tipoproducto, color, Double.parseDouble(precio), cantidad);
        }
    }//GEN-LAST:event_lstProductosValueChanged
    private void jmArchivoActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //Vamos a tener la logica de la importacion
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Es importante que el archivo a importar tenga el nombre "+
                        "inventario.csv y se encuentre en la raiz del proyecto",
                "Importacion de Datos desde archivo CSV",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    }
    private void jmiImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImportarActionPerformed
        // Muestra un cuadro de dialogo preguntando si deseamos eliminar
         int respuesta =  JOptionPane.showConfirmDialog(this,
                "Es importante que el archivo a importar tenga el nombre "+
                        "Inventario_Papeleria.csv y se encuentre en el raiz del proyecto", 
                "Importacion de Datos desde archivo CSV",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Si la respuesta es Si comienza a eliminar el reegistro
        if (respuesta == JOptionPane.YES_OPTION) {
            clsCsv cCsv = new clsCsv();
            cCsv.importarDatos();
        }
    }//GEN-LAST:event_jmiImportarActionPerformed

    private void jmiExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExportarActionPerformed
        try {
        // 1. Preparamos una lista (La "caja") para guardar todos los artículos temporalmente en RAM
        List<clsProductos> listaProductos = new ArrayList<>();
       
        // 2. Abrimos el archivo de texto plano para lectura
        BufferedReader br = new BufferedReader(new FileReader("listado_producto.txt"));
        String linea;
       
        // 3. Recorremos el archivo secuencial línea por línea
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split("\\|");
           
            // Verificamos que la línea tenga las 3 partes para evitar errores
            if (datos.length >= 3) {
                // Parseamos el precio a double
                double precioParseado = Double.parseDouble(datos[2]);
               
                // Creamos el objeto y lo metemos a la lista
                clsProductos nuevoProducto = new clsProductos(datos[0], datos[1], datos[2], datos[3], Double.parseDouble(datos[4]), datos[5]);
                listaProductos.add(nuevoProducto);
            }
        }
        br.close(); // Siempre cerrar el flujo de lectura
       
        // ==========================================
        // 4. LA MAGIA DE GSON (Serialización Masiva)
        // ==========================================
       
        // TIP DE INGENIERÍA: En lugar de usar 'new Gson()', usamos GsonBuilder
        // con 'setPrettyPrinting' para que el archivo salga formateado con tabulaciones
        // y saltos de línea (ideal para que los alumnos lo puedan leer fácil).
        Gson gson = new GsonBuilder().setPrettyPrinting().create();
       
        // Convertimos TODA la lista a un solo String con formato JSON
        String jsonFinal = gson.toJson(listaProductos);
       
        // 5. Guardamos el String gigante en un archivo nuevo .json
        BufferedWriter bw = new BufferedWriter(new FileWriter("respado_producto.json"));
        bw.write(jsonFinal);
        bw.close();
       
        JOptionPane.showMessageDialog(this, "¡Exportación masiva a JSON exitosa!");
       
    } catch (Exception e) {
        System.out.println(" Error durante la exportación a JSON: " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jmiExportarActionPerformed

    private void jmiGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGenerarReporteActionPerformed
        // 1. Instanciamos el documento (La "hoja" en blanco)
        Document documento = new Document();

        try {
            // 2. Preparamos el escritor para guardar el archivo en el disco duro
            PdfWriter.getInstance(documento, new FileOutputStream("Reporte_Inventario.pdf"));

            // 3. Abrimos el documento para empezar a escribirle
            documento.open();
            
            //Agregamos la imagen al reporte
            try{
                Image logo = Image.getInstance("Logo.jpg");
                logo.scaleToFit(200, 200);
                logo.setAlignment(Element.ALIGN_RIGHT);
                documento.add(logo);
            } catch (Exception e) {
            System.out.println("Avisos: No se encontro la imagen del logo. " + e.getMessage());
            }
            // 4. Agregamos un Título
            documento.add(new Paragraph("Reporte Gerencial de Inventario - Taller 360"));
            documento.add(new Paragraph("Logo.jpg")); // Un salto de línea para dar espacio

            // 5. Creamos la estructura tabular (3 columnas)
            PdfPTable tabla = new PdfPTable(4);

            // 6. Agregamos los encabezados de la tabla
            tabla.addCell("CÓDIGO");
            tabla.addCell("DESCRIPCIÓN");
            tabla.addCell("PRECIO ($)");
            tabla.addCell("ESTADO");

            //7. Toma los daros desde el txt y los muestra en el PDF
            BufferedReader br = new BufferedReader(new FileReader("listado_producto.txt"));
            String linea;
            double total = 0;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");
                if(datos.length >= 3){
                    tabla.addCell(datos[0]);
                    tabla.addCell(datos[1]);
                    tabla.addCell(datos[2]);
                    total = total + Double.parseDouble(datos[2]);
                    if (Math.random() > 0.5){
                        tabla.addCell("Agotado");
                    }else {
                        tabla.addCell("Disponible");
                    }
                }
           }
           br.close();

            // 8. Inyectamos la tabla terminada dentro del documento PDF
            documento.add(tabla);

            // 9. Cerramos el documento (¡Importantísimo para que se guarde el archivo!)
            documento.close();

            // Mensaje de éxito para el usuario
            javax.swing.JOptionPane.showMessageDialog(this, "¡PDF generado con éxito en la carpeta del proyecto!");

        } catch (Exception e) {
            System.out.println("Error al generar el PDF: " + e.getMessage());
        }                                        
    }//GEN-LAST:event_jmiGenerarReporteActionPerformed

    private void jmiReporteBonitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteBonitoActionPerformed
        // 1. Configuramos fuentes profesionales (Tamaños y Colores)
        Font fuenteTitulo = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
        Font fuenteSubtitulo = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.DARK_GRAY);
        Font fuenteCabeceraTabla = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.WHITE);

        Document documento = new Document();

        try {
            // Preparamos el escritor
            PdfWriter.getInstance(documento, new FileOutputStream("Reporte_Inventario.pdf"));
            documento.open();

            // 2. Agregamos el Logo (Alineado a la derecha)
            try {
                Image logo = Image.getInstance("Logo.jpg");
                logo.scaleToFit(120, 80); 
                logo.setAlignment(Element.ALIGN_RIGHT);
                documento.add(logo);
            } catch (Exception e) {
                System.out.println("Aviso: No se encontró la imagen del logo.");
            }
            
            // 3. Encabezado Corporativo de la Empresa
            Paragraph nombreEmpresa = new Paragraph("TALLER 360 S.A. DE C.V.", fuenteTitulo);
            nombreEmpresa.setAlignment(Element.ALIGN_LEFT);
            documento.add(nombreEmpresa);

            Paragraph tituloReporte = new Paragraph("Reporte Gerencial de Inventario", fuenteSubtitulo);
            documento.add(tituloReporte);

            // Agregamos la fecha y hora exacta del reporte
            String fechaActual = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date());
            Paragraph fecha = new Paragraph("Fecha de impresión: " + fechaActual, fuenteSubtitulo);
            fecha.setSpacingAfter(20f); // Damos 20 puntos de espacio antes de que empiece la tabla
            documento.add(fecha);

            // 4. Mejoramos la estructura de la Tabla
            PdfPTable tabla = new PdfPTable(4);
            tabla.setWidthPercentage(100); // El ancho de la hoja
            tabla.setWidths(new float[]{2f, 5f, 2f, 2f}); // Tamaños relativos la descripción (5f)

            // 5. Cabeceras con Estilo y Color de Fondo
            String[] cabeceras = {"CÓDIGO", "DESCRIPCIÓN", "PRECIO ($)", "STATUS"};
            for (String texto : cabeceras) {
                PdfPCell celda = new PdfPCell(new Phrase(texto, fuenteCabeceraTabla));
                celda.setBackgroundColor(new BaseColor(41, 128, 185)); // Un azul
                celda.setHorizontalAlignment(Element.ALIGN_CENTER);
                celda.setPadding(8f); // Agregamos especiado a las cabeceras
                tabla.addCell(celda);
            }
            
            // 6. Lectura de datos desde el archivo .txt
            BufferedReader br = new BufferedReader(new FileReader("listado_producto.txt"));
            String linea;
            double totalInversion = 0;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split("\\|");
                if (datos.length >= 3) {

                    // Usamos PdfPCell para inyectar los datos, así podemos alinear los textos
                    tabla.addCell(new PdfPCell(new Phrase(datos[0])));
                    tabla.addCell(new PdfPCell(new Phrase(datos[1])));

                    // El precio lo alineamos a la derecha (estándar contable)
                    PdfPCell celdaPrecio = new PdfPCell(new Phrase("$" + datos[2]));
                    celdaPrecio.setHorizontalAlignment(Element.ALIGN_RIGHT);
                    tabla.addCell(celdaPrecio);

                    try {
                        totalInversion += Double.parseDouble(datos[2]);
                    } catch (Exception e) {}

                    String status = (Math.random() > 0.5) ? "Disponible" : "Agotado";
                    PdfPCell celdaStatus = new PdfPCell(new Phrase(status));
                    celdaStatus.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tabla.addCell(celdaStatus);
                }
            }
            br.close();

            // Inyectamos la tabla al documento
            documento.add(tabla);

            // 7. Resaltamos el Total al final del reporte
            Font fuenteTotal = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.RED);
            Paragraph textoTotal = new Paragraph("\nInversión Total en Inventario: $" + String.format("%.2f", totalInversion), fuenteTotal);
            textoTotal.setAlignment(Element.ALIGN_RIGHT); 
            documento.add(textoTotal);

            documento.close();
            javax.swing.JOptionPane.showMessageDialog(this, "¡PDF generado con éxito en la carpeta del proyecto!");

        } catch (Exception e) {
            System.out.println("Error al generar el PDF: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiReporteBonitoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int repuesta = JOptionPane.showConfirmDialog(
                this,"Deseas eliminar el registro?",
                "Eliminar registro",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(repuesta == JOptionPane.YES_OPTION){
            updateProductos.eliminar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmProductos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblCantidad;
    private javax.swing.JLabel IblCantidad1;
    private javax.swing.JLabel IblCantidad2;
    private javax.swing.JLabel IblCantidad3;
    private javax.swing.JLabel IblCantidad4;
    private javax.swing.JLabel IblCodigo;
    private javax.swing.JLabel IblColor;
    private javax.swing.JLabel IblColor1;
    private javax.swing.JLabel IblColor2;
    private javax.swing.JLabel IblDescripcion;
    private javax.swing.JLabel IblIDProducto;
    private javax.swing.JLabel IblIDProducto1;
    private javax.swing.JLabel IblIDProducto2;
    private javax.swing.JLabel IblNombreProducto;
    private javax.swing.JLabel IblNombreProducto1;
    private javax.swing.JLabel IblNombreProducto2;
    private javax.swing.JLabel IblPrecio;
    private javax.swing.JLabel IblPrecio1;
    private javax.swing.JLabel IblPrecio2;
    private javax.swing.JLabel IblPrecio3;
    private javax.swing.JLabel IblTipoProducto;
    private javax.swing.JLabel IblTipoProducto1;
    private javax.swing.JLabel IblTipoProducto2;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmiExportar;
    private javax.swing.JMenuItem jmiGenerarReporte;
    private javax.swing.JMenuItem jmiImportar;
    private javax.swing.JMenuItem jmiReporteBonito;
    private javax.swing.JList<String> lstProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtColor1;
    private javax.swing.JTextField txtIDProducto;
    private javax.swing.JTextField txtIDProducto1;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProducto1;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtTipoProducto;
    private javax.swing.JTextField txtTipoProducto1;
    // End of variables declaration//GEN-END:variables
}